vaadin:
    launch-browser: true
    allowed-packages:
        - com.vaadin
        - org.vaadin
        - com.example.application
    exclude-urls:
        - "/swagger-ui/**"
        - "/actuator/**"
        - "/ecommerce-ui/files/**"
        - "/v3/api-docs/**"
        - "/api/v1/**"

spring:
    mustache:
        check-template-location: false
    application:
        name: DOCTOR-APPOINTMENT

    datasource:
        url: jdbc:mysql://localhost:3306/doctor_appointment?allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: password
    jpa:
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
        hibernate:
            ddl-auto: update